### ISSUE TITLE
feature request: timestamp -> ulid

### ISSUE THREAD

**Issue by mmisiewicz** [andrielfn/pg-ulid#1]
Hi! thanks for the great extension. 

It would be cool if there was a cast function to go from timestamp to a zero'd out ULID. This would be symmetrical with the existing ULID -> timestamp cast.

**Comment by andrielfn** [comment]
Hey @mmisiewicz, I've just [pushed](https://github.com/andrielfn/pg-ulid/commit/8983b72c133caa3a71e6b5bc3e6aa3c6fc4a5cc4) the support for timestamp -> ulid conversion.

This looks like the following.
```
tests=# SELECT '2023-11-16 19:30:15'::timestamp::ulid;
            ulid
----------------------------
 01HFCSSMAR000D4VZYZS62E9A1
(1 row)

tests=# SELECT '01HFCSSMAR000D4VZYZS62E9A1'::ulid::timestamp;
      timestamp
---------------------
 2023-11-16 19:30:15
(1 row)

tests=# SELECT timestamp_to_ulid('2023-11-16 19:30:15'::timestamp);
     timestamp_to_ulid
----------------------------
 01HFCSSMAR64PV36YTY55JDXK7
(1 row)
```

Let me know if that makes sense.

**Comment by mmisiewicz** [comment]
This is exactly what I'm looking for! Awesome!

On November 16, 2023, GitHub notifications ***@***.***>
wrote:
> Hey @mmisiewicz <https://github.com/mmisiewicz>, I've just pushed
> <https://github.com/andrielfn/pg-
> ulid/commit/8983b72c133caa3a71e6b5bc3e6aa3c6fc4a5cc4> the support for
> timestamp -> ulid conversion.
>
> This looks like the following.
>
> tests=# SELECT '2023-11-16 19:30:15'::timestamp::ulid; ulid
> ---------------------------- 01HFCSSMAR000D4VZYZS62E9A1 (1 row)
> tests=# SELECT '01HFCSSMAR000D4VZYZS62E9A1'::ulid::timestamp;
> timestamp --------------------- 2023-11-16 19:30:15 (1 row) tests=#
> SELECT timestamp_to_ulid('2023-11-16 19:30:15'::timestamp);
> timestamp_to_ulid ----------------------------
> 01HFCSSMAR64PV36YTY55JDXK7 (1 row)
> Let me know if that makes sense.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/andrielfn/pg-ulid/issues/1#issuecomment-1815379873>,
or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAM6NBMWTNPBGG2QLCSL3HDYE2EAFAVCNFSM6AAAAAA6U7RUG2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMJVGM3TSOBXGM>.
You are receiving this because you were mentioned.Message ID:
***@***.***>
